spring:
  datasource:
    url: jdbc:mysql://192.168.1.117:3306/product?characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: PRODUCT
---
spring:
  profiles: dev    
image:
  path: F:/image/
  server:
    path: http://localhost:8000/product/image/
    
    
---
spring:
  profiles: test  
image:
  path: /opt/microservice/images/
  server:
    path: http://192.168.1.117:10001/product/image/