eureka:
  instance:
    prefer-ip-address: true
    hostname: GATEWAY-SERVER
    instance-id: GATEWAY-SERVER-ID
 
spring:
  profiles:
    active: dev
  application:
    name: GATEWAY
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: product-server-route
        uri: lb://CONFIGCLIENT-GIT
        predicates:
        - Path=/product-server/**
        filters:
        - StripPrefix=1
      - id: customer-server-route
        uri: lb://CUSTOMER
        predicates:
        - Path=/customer-server/**
        filters:
        - StripPrefix=1
      - id: config-client-route
        uri: lb://CONFIGCLIENT-GIT
        predicates:
        - Path=/config-client/**
        filters:
        - StripPrefix=1
