spring:
  datasource:
    url: jdbc:mysql://localhost:3306/customer?characterEncoding=utf8&useSSL=false
    username: root
    password: robert
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    #          show-sql: true
    ##    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  application:
    name: CUSTOMER
    
 eureka:
  instance:
    prefer-ip-address: true
    hostname: CUSTOMER-SERVER
    instance-id: CUSTOMER-SERVER-ID
    
---
spring:
  profiles: dev    

    
    
---
spring:
  profiles: test  
