spring:
  application:
    name: CONFIGCLIENT-GIT
eureka:
  instance:
    prefer-ip-address: true
    hostname: CONFIGCLIENT
    instance-id: CONFIGCLIENT-ID

---
spring:
  profiles: dev
server:
  port: 10006

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10000/eureka/
models: 
  profile:
    type: dev
    name: aa开发环境aa
    

---
spring:
  profiles: test
server:
  port: 10006

eureka:
  client:
    serviceUrl:
      defaultZone: http://formssi-eureka:10000/eureka/
      
models: 
  profile:
    type: test
    name: 测试环境222
